package graphql.archunit

import com.tngtech.archunit.core.domain.JavaClasses
import com.tngtech.archunit.core.importer.ClassFileImporter
import com.tngtech.archunit.core.importer.ImportOption
import spock.lang.Specification

/**
 * Ensures that inner/nested classes are not used (except Builders).
 * Each class/interface should be in its own file. See coding-guidelines.md.
 */
class InnerClassUsageTest extends Specification {

    private static final JavaClasses importedClasses = new ClassFileImporter()
            .withImportOption(ImportOption.Predefined.DO_NOT_INCLUDE_TESTS)
            .importPackages("graphql")

    private static final Set<String> EXEMPTION_LIST = [
            "graphql.DirectivesUtil\$DirectivesHolder",
            "graphql.GraphQLUnusualConfiguration\$BaseConfig",
            "graphql.GraphQLUnusualConfiguration\$BaseContextConfig",
            "graphql.GraphQLUnusualConfiguration\$DataloaderConfig",
            "graphql.GraphQLUnusualConfiguration\$GoodFaithIntrospectionConfig",
            "graphql.GraphQLUnusualConfiguration\$GraphQLContextConfiguration",
            "graphql.GraphQLUnusualConfiguration\$IncrementalSupportConfig",
            "graphql.GraphQLUnusualConfiguration\$ParserConfig",
            "graphql.GraphQLUnusualConfiguration\$PropertyDataFetcherConfig",
            "graphql.GraphQLUnusualConfiguration\$ResponseMapFactoryConfig",
            "graphql.GraphqlErrorBuilder\$GraphqlErrorImpl",
            "graphql.GraphqlErrorException\$BuilderBase",
            "graphql.ProfilerResult\$DataFetcherResultType",
            "graphql.ProfilerResult\$DataFetcherType",
            "graphql.ProfilerResult\$DispatchEvent",
            "graphql.ProfilerResult\$DispatchEventType",
            "graphql.TypeMismatchError\$GraphQLTypeToTypeKindMapping",
            "graphql.analysis.MaxQueryComplexityInstrumentation\$State",
            "graphql.analysis.values.ValueTraverser\$InputElements",
            "graphql.analysis.values.ValueVisitor\$InputElements",
            "graphql.execution.Async\$CombinedBuilder",
            "graphql.execution.Async\$Empty",
            "graphql.execution.Async\$Many",
            "graphql.execution.Async\$Single",
            "graphql.execution.EngineRunningObserver\$RunningState",
            "graphql.execution.FieldValueInfo\$CompleteValueType",
            "graphql.execution.MergedField\$MultiMergedField",
            "graphql.execution.ValuesResolver\$ValueMode",
            "graphql.execution.incremental.DeferredExecutionSupport\$DeferredExecutionSupportImpl",
            "graphql.execution.incremental.DeferredExecutionSupport\$NoOp",
            "graphql.execution.incremental.DeferredFragmentCall\$FieldWithExecutionResult",
            "graphql.execution.instrumentation.ChainedInstrumentation\$ChainedDeferredExecutionStrategyInstrumentationContext",
            "graphql.execution.instrumentation.ChainedInstrumentation\$ChainedExecuteObjectInstrumentationContext",
            "graphql.execution.instrumentation.ChainedInstrumentation\$ChainedExecutionStrategyInstrumentationContext",
            "graphql.execution.instrumentation.ChainedInstrumentation\$ChainedFieldFetchingInstrumentationContext",
            "graphql.execution.instrumentation.ChainedInstrumentation\$ChainedInstrumentationContext",
            "graphql.execution.instrumentation.ChainedInstrumentation\$ChainedInstrumentationFunction",
            "graphql.execution.instrumentation.ChainedInstrumentation\$ChainedInstrumentationState",
            "graphql.execution.instrumentation.dataloader.ExhaustedDataLoaderDispatchStrategy\$CallStack",
            "graphql.execution.instrumentation.dataloader.PerLevelDataLoaderDispatchStrategy\$CallStack",
            "graphql.execution.instrumentation.dataloader.PerLevelDataLoaderDispatchStrategy\$CallStack\$StateForLevel",
            "graphql.execution.instrumentation.dataloader.PerLevelDataLoaderDispatchStrategy\$ChainedDLStack",
            "graphql.execution.instrumentation.dataloader.PerLevelDataLoaderDispatchStrategy\$ChainedDLStack\$StateForLevel",
            "graphql.execution.instrumentation.fieldvalidation.FieldValidationSupport\$FieldAndArgError",
            "graphql.execution.instrumentation.fieldvalidation.FieldValidationSupport\$FieldAndArgumentsImpl",
            "graphql.execution.instrumentation.fieldvalidation.FieldValidationSupport\$FieldValidationEnvironmentImpl",
            "graphql.execution.instrumentation.parameters.InstrumentationReactiveResultsParameters\$ResultType",
            "graphql.execution.instrumentation.tracing.TracingInstrumentation\$Options",
            "graphql.execution.instrumentation.tracing.TracingSupport\$TracingContext",
            "graphql.execution.reactive.NonBlockingMutexExecutor\$RunNode",
            "graphql.execution.reactive.ReactiveSupport\$AtTheEndPublisher",
            "graphql.execution.reactive.ReactiveSupport\$FlowPublisherToCompletableFuture",
            "graphql.execution.reactive.ReactiveSupport\$PublisherToCompletableFuture",
            "graphql.execution.reactive.SingleSubscriberPublisher\$OnSubscriptionCallback",
            "graphql.execution.reactive.SingleSubscriberPublisher\$SimpleSubscription",
            "graphql.i18n.I18n\$BundleType",
            "graphql.introspection.GoodFaithIntrospection\$BadFaithIntrospectionError",
            "graphql.introspection.Introspection\$DirectiveLocation",
            "graphql.introspection.Introspection\$TypeKind",
            "graphql.introspection.IntrospectionQueryBuilder\$Options",
            "graphql.introspection.IntrospectionWithDirectivesSupport\$DirectivePredicate",
            "graphql.introspection.IntrospectionWithDirectivesSupport\$DirectivePredicateEnvironment",
            "graphql.language.AstPrinter\$NodePrinter",
            "graphql.language.IgnoredChar\$IgnoredCharKind",
            "graphql.language.NodeUtil\$DirectivesHolder",
            "graphql.language.NodeUtil\$GetOperationResult",
            "graphql.language.OperationDefinition\$Operation",
            "graphql.language.PrettyAstPrinter\$PrettyPrinterOptions",
            "graphql.language.PrettyAstPrinter\$PrettyPrinterOptions\$IndentType",
            "graphql.language.SchemaDefinition\$Builder",
            "graphql.language.SchemaExtensionDefinition\$Builder",
            "graphql.normalized.ExecutableNormalizedOperationFactory\$ExecutableNormalizedOperationFactoryImpl",
            "graphql.normalized.ExecutableNormalizedOperationFactory\$ExecutableNormalizedOperationFactoryImpl\$CollectedField",
            "graphql.normalized.ExecutableNormalizedOperationFactory\$ExecutableNormalizedOperationFactoryImpl\$CollectedFieldGroup",
            "graphql.normalized.ExecutableNormalizedOperationFactory\$ExecutableNormalizedOperationFactoryImpl\$PossibleMerger",
            "graphql.normalized.ExecutableNormalizedOperationFactory\$Options",
            "graphql.normalized.ExecutableNormalizedOperationToAstCompiler\$CompilerResult",
            "graphql.normalized.ExecutableNormalizedOperationToAstCompiler\$ExecutionFragmentDetails",
            "graphql.normalized.nf.NormalizedDocument\$NormalizedOperationWithAssumedSkipIncludeVariables",
            "graphql.normalized.nf.NormalizedDocumentFactory\$NormalizedDocumentFactoryImpl",
            "graphql.normalized.nf.NormalizedDocumentFactory\$NormalizedDocumentFactoryImpl\$CollectedField",
            "graphql.normalized.nf.NormalizedDocumentFactory\$NormalizedDocumentFactoryImpl\$CollectedFieldGroup",
            "graphql.normalized.nf.NormalizedDocumentFactory\$NormalizedDocumentFactoryImpl\$PossibleMerger",
            "graphql.normalized.nf.NormalizedDocumentFactory\$Options",
            "graphql.normalized.nf.NormalizedOperationToAstCompiler\$CompilerResult",
            "graphql.parser.MultiSourceReader\$SourceAndLine",
            "graphql.parser.MultiSourceReader\$SourcePart",
            "graphql.parser.NodeToRuleCapturingParser\$ParserContext",
            "graphql.parser.ParsingListener\$Token",
            "graphql.relay.Relay\$ResolvedGlobalId",
            "graphql.schema.DataFetchingEnvironmentImpl\$DFEInternalState",
            "graphql.schema.DataFetchingFieldSelectionSetImpl\$SelectedFieldImpl",
            "graphql.schema.GraphQLSchema\$BuilderWithoutTypes",
            "graphql.schema.GraphQLSchema\$FastBuilder",
            "graphql.schema.GraphQLTypeResolvingVisitor\$TypeRefResolvingVisitor",
            "graphql.schema.InputValueWithState\$State",
            "graphql.schema.PropertyFetchingImpl\$CacheKey",
            "graphql.schema.PropertyFetchingImpl\$CachedLambdaFunction",
            "graphql.schema.PropertyFetchingImpl\$CachedMethod",
            "graphql.schema.PropertyFetchingImpl\$FastNoSuchMethodException",
            "graphql.schema.PropertyFetchingImpl\$MethodFinder",
            "graphql.schema.SchemaTransformer\$DummyRoot",
            "graphql.schema.SchemaTransformer\$RelevantZippersAndBreadcrumbs",
            "graphql.schema.SchemaTransformer\$ZipperWithOneParent",
            "graphql.schema.SchemaTraverser\$TraverserDelegateListVisitor",
            "graphql.schema.SchemaTraverser\$TraverserDelegateVisitor",
            "graphql.schema.ShallowTypeRefCollector\$InterfaceInterfaceReplaceTarget",
            "graphql.schema.ShallowTypeRefCollector\$ObjectInterfaceReplaceTarget",
            "graphql.schema.ShallowTypeRefCollector\$UnionTypesReplaceTarget",
            "graphql.schema.diff.SchemaDiff\$CountingReporter",
            "graphql.schema.diff.SchemaDiff\$Options",
            "graphql.schema.diffing.DiffImpl\$MappingEntry",
            "graphql.schema.diffing.DiffImpl\$OptimalEdit",
            "graphql.schema.diffing.EditOperation\$Operation",
            "graphql.schema.diffing.PossibleMappingsCalculator\$PossibleMappings",
            "graphql.schema.diffing.PossibleMappingsCalculator\$VertexContextSegment",
            "graphql.schema.diffing.Vertex\$VertexData",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveArgumentAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveArgumentDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveArgumentRename",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveArgumentValueModification",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveDifference",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveDirectiveArgumentLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveEnumLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveEnumValueLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveInputObjectFieldLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveInputObjectLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveInterfaceFieldArgumentLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveInterfaceFieldLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveInterfaceLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveLocationDetail",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveObjectFieldArgumentLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveObjectFieldLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveObjectLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveRenamed",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveScalarLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveSchemaLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$AppliedDirectiveUnionLocation",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveArgumentAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveArgumentDefaultValueModification",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveArgumentDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveArgumentRename",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveArgumentTypeModification",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveDifference",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveModification",
            "graphql.schema.diffing.ana.SchemaDifference\$DirectiveModificationDetail",
            "graphql.schema.diffing.ana.SchemaDifference\$EnumAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$EnumDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$EnumDifference",
            "graphql.schema.diffing.ana.SchemaDifference\$EnumModification",
            "graphql.schema.diffing.ana.SchemaDifference\$EnumModificationDetail",
            "graphql.schema.diffing.ana.SchemaDifference\$EnumValueAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$EnumValueDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$EnumValueRenamed",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectDifference",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectFieldAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectFieldDefaultValueModification",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectFieldDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectFieldRename",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectFieldTypeModification",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectModification",
            "graphql.schema.diffing.ana.SchemaDifference\$InputObjectModificationDetail",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceDifference",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldArgumentAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldArgumentDefaultValueModification",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldArgumentDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldArgumentRename",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldArgumentTypeModification",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldRename",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceFieldTypeModification",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceInterfaceImplementationAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceInterfaceImplementationDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceModification",
            "graphql.schema.diffing.ana.SchemaDifference\$InterfaceModificationDetail",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectDifference",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldArgumentAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldArgumentDefaultValueModification",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldArgumentDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldArgumentRename",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldArgumentTypeModification",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldRename",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectFieldTypeModification",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectInterfaceImplementationAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectInterfaceImplementationDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectModification",
            "graphql.schema.diffing.ana.SchemaDifference\$ObjectModificationDetail",
            "graphql.schema.diffing.ana.SchemaDifference\$ScalarAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$ScalarDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$ScalarDifference",
            "graphql.schema.diffing.ana.SchemaDifference\$ScalarModification",
            "graphql.schema.diffing.ana.SchemaDifference\$ScalarModificationDetail",
            "graphql.schema.diffing.ana.SchemaDifference\$SchemaAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$SchemaDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$SchemaModification",
            "graphql.schema.diffing.ana.SchemaDifference\$SchemaModificationDetail",
            "graphql.schema.diffing.ana.SchemaDifference\$UnionAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$UnionDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$UnionDifference",
            "graphql.schema.diffing.ana.SchemaDifference\$UnionMemberAddition",
            "graphql.schema.diffing.ana.SchemaDifference\$UnionMemberDeletion",
            "graphql.schema.diffing.ana.SchemaDifference\$UnionModification",
            "graphql.schema.diffing.ana.SchemaDifference\$UnionModificationDetail",
            "graphql.schema.idl.SchemaDirectiveWiringSchemaGeneratorPostProcessing\$Visitor",
            "graphql.schema.idl.SchemaGenerator\$Options",
            "graphql.schema.idl.SchemaGeneratorDirectiveHelper\$EnvBuilder",
            "graphql.schema.idl.SchemaGeneratorDirectiveHelper\$EnvInvoker",
            "graphql.schema.idl.SchemaGeneratorDirectiveHelper\$Parameters",
            "graphql.schema.idl.SchemaGeneratorHelper\$BuildContext",
            "graphql.schema.idl.SchemaPrinter\$Options",
            "graphql.schema.idl.SchemaPrinter\$SchemaElementPrinter",
            "graphql.schema.transform.FieldVisibilitySchemaTransformation\$FieldRemovalVisitor",
            "graphql.schema.transform.FieldVisibilitySchemaTransformation\$TypeObservingVisitor",
            "graphql.schema.transform.FieldVisibilitySchemaTransformation\$TypeRemovalVisitor",
            "graphql.schema.transform.VisibleFieldPredicateEnvironment\$VisibleFieldPredicateEnvironmentImpl",
            "graphql.schema.visitor.GraphQLSchemaTraversalControl\$Control",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$AppliedDirectiveArgumentVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$AppliedDirectiveVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$ArgumentVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$DirectiveVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$EnumTypeVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$EnumValueDefinitionVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$FieldDefinitionVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$InputObjectFieldVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$InputObjectTypeVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$InterfaceTypeVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$ObjectVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$ScalarTypeVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$SchemaElementVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitor\$UnionTypeVisitorEnvironment",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$AppliedDirectiveArgumentEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$AppliedDirectiveEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$ArgumentEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$DirectiveEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$EnumTypeEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$EnumValueDefinitionEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$FieldDefinitionEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$InputObjectFieldEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$InputObjectTypeEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$InterfaceTypeEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$ObjectEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$ScalarTypeEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$SchemaElementEnv",
            "graphql.schema.visitor.GraphQLSchemaVisitorAdapter\$UnionTypeEnv",
            "graphql.util.Anonymizer\$AnonymizeResult",
            "graphql.util.CyclicSchemaAnalyzer\$FindCyclesImpl",
            "graphql.util.CyclicSchemaAnalyzer\$GraphAndIndex",
            "graphql.util.CyclicSchemaAnalyzer\$SchemaCycle",
            "graphql.util.FpKit\$ArrayIterator",
            "graphql.util.LockKit\$ComputedOnce",
            "graphql.util.LockKit\$ReentrantLock",
            "graphql.util.NodeZipper\$ModificationType",
            "graphql.util.TraverserContext\$Phase",
            "graphql.util.TraverserState\$EndList",
            "graphql.util.TraverserState\$QueueTraverserState",
            "graphql.util.TraverserState\$StackTraverserState",
            "graphql.util.TreeParallelTransformer\$EnterAction",
            "graphql.util.TreeParallelTraverser\$EnterAction",
            "graphql.util.querygenerator.QueryGeneratorFieldSelection\$FieldSelection",
            "graphql.util.querygenerator.QueryGeneratorFieldSelection\$FieldSelectionResult",
            "graphql.util.querygenerator.QueryGeneratorOptions\$QueryGeneratorOptionsBuilder",
            "graphql.validation.OperationValidator\$Conflict",
            "graphql.validation.OperationValidator\$FieldAndType",
            "graphql.validation.ValidationErrorCollector\$MaxValidationErrorsReached",
    ] as Set

    def "should not use inner classes - each class or interface should be in its own file"() {
        when:
        def innerClasses = importedClasses.stream()
                .filter { javaClass ->
                    def name = javaClass.name
                    name.contains('$') &&
                            !(name =~ /\$\d+/) &&                    // not anonymous
                            !name.contains('$$') &&                   // not synthetic/lambda
                            !name.endsWith('$Builder') &&             // Builders are allowed
                            !name.startsWith("graphql.parser.antlr.") // ANTLR-generated code
                }
                .map { it.name }
                .filter { !EXEMPTION_LIST.contains(it) }
                .sorted()
                .collect()

        then:
        if (!innerClasses.isEmpty()) {
            throw new AssertionError("""The following inner/nested classes should be moved to their own files:
${innerClasses.join("\n")}

Each class/interface should be in its own file. See coding-guidelines.md.
If a class must remain as an inner class, add it to the exemption list in ${InnerClassUsageTest.class.simpleName}.groovy.""")
        }
    }

    def "exempted classes should actually exist as inner classes"() {
        when:
        def exemptedButMissing = EXEMPTION_LIST.findAll { exemptedClassName ->
            !importedClasses.stream()
                    .anyMatch { it.name == exemptedClassName }
        }.sort()

        then:
        if (!exemptedButMissing.isEmpty()) {
            throw new AssertionError("""The following classes are in the exemption list but no longer exist:
${exemptedButMissing.join("\n")}

Please remove them from the exemption list in ${InnerClassUsageTest.class.simpleName}.groovy.""")
        }
    }
}
