package graphql.arbitrary

import graphql.schema.GraphQLEnumType
import graphql.schema.GraphQLInputObjectField
import graphql.schema.GraphQLInputObjectType
import graphql.schema.GraphQLInputType
import graphql.schema.GraphQLList
import graphql.schema.GraphQLNonNull
import graphql.schema.GraphQLScalarType
import graphql.schema.GraphQLSchema
import graphql.schema.GraphQLTypeUtil
import io.kotest.property.Arb
import io.kotest.property.RandomSource
import io.kotest.property.arbitrary.int
import io.kotest.property.arbitrary.next
import io.kotest.property.arbitrary.numericDouble
import io.kotest.property.arbitrary.of
import io.kotest.property.arbitrary.string

/**
 * Generates external variable values accepted by graphql-java for a GraphQL input type.
 *
 * Generation observes nullability, oneOf semantics, defaults, list coercion, and recursive input
 * object cycles. Unknown custom scalars require an entry in [ScalarValueOverrides]. String ID
 * values are generated by [IDValueGenFactory].
 */
internal class GraphQLExternalInputValueGen(
    schema: GraphQLSchema,
    private val config: Config,
    private val randomSource: RandomSource,
    private val uncoercedValueWeight: Double = 0.0,
    private val allEdgesGraph: CycleGroups = CycleGroups.allInputCycles(schema),
    private val mandatoryEdgesGraph: CycleGroups = CycleGroups.mandatoryInputCycles(schema)
) {
    private val idValueGen by lazy {
        config[IDValueGenFactory](IDValueGen.Factory.Params(schema, config, randomSource))
    }

    private data class Ctx(
        val type: GraphQLInputType,
        val depth: Int = 0,
        val maxDepth: Int,
        val nullable: Boolean = true
    ) {
        val overBudget: Boolean
            get() = depth >= maxDepth

        fun push(
            nextType: GraphQLInputType,
            nullable: Boolean = nextType !is GraphQLNonNull
        ): Ctx =
            copy(type = nextType, depth = depth + 1, nullable = nullable)

        fun unwrap(
            nextType: GraphQLInputType,
            nullable: Boolean
        ): Ctx = copy(type = nextType, nullable = nullable)
    }

    fun gen(type: GraphQLInputType): Any? =
        gen(Ctx(type = type, maxDepth = config[MaxValueDepth]))

    private fun gen(ctx: Ctx): Any? {
        val type = ctx.type
        if (type is GraphQLNonNull) {
            return gen(ctx.unwrap(type.wrappedType as GraphQLInputType, nullable = false))
        }
        if (ctx.nullable && shouldGenerateNull(ctx)) return null
        if (type is GraphQLList) return genList(type, ctx)
        if (type is GraphQLScalarType) return genScalar(type)
        if (type is GraphQLEnumType) return Arb.of(type.values).next(randomSource).name
        if (type is GraphQLInputObjectType && type.isOneOf) return genOneOf(type, ctx)
        if (type is GraphQLInputObjectType) return genInputObject(type, ctx)
        throw UnsupportedOperationException("Unsupported input type: $type")
    }

    private fun shouldGenerateNull(ctx: Ctx): Boolean =
        ctx.overBudget || randomSource.sampleWeight(config[ExplicitNullValueWeight])

    private fun genList(
        listType: GraphQLList,
        ctx: Ctx
    ): Any? {
        val wrappedType = listType.wrappedType as GraphQLInputType
        val itemContext = ctx.push(wrappedType)
        val canUseSingleValueCoercion = GraphQLTypeUtil.unwrapNonNull(wrappedType) !is GraphQLList
        if (canUseSingleValueCoercion && !itemContext.overBudget && randomSource.sampleWeight(uncoercedValueWeight)) {
            return gen(ctx.push(wrappedType, nullable = false))
        }
        val size = if (itemContext.overBudget) 0 else Arb.int(config[ListValueSize]).next(randomSource)
        return List(size) { gen(itemContext) }
    }

    private fun genScalar(type: GraphQLScalarType): Any? {
        config[ScalarValueOverrides][type.name]?.let { return it.next(randomSource) }
        return when (type.name) {
            "Boolean" -> randomSource.random.nextBoolean()
            "Float" -> genFloat()
            "Int" -> Arb.int().next(randomSource)
            "ID" -> genId()
            "String" -> genString()
            else -> throw UnsupportedOperationException(
                "No external value generator configured for scalar `${type.name}`"
            )
        }
    }

    private fun genFloat(): Number =
        if (randomSource.sampleWeight(uncoercedValueWeight)) {
            Arb.int().next(randomSource)
        } else {
            Arb.numericDouble().next(randomSource)
        }

    private fun genId(): Any =
        if (randomSource.sampleWeight(uncoercedValueWeight)) {
            Arb.int().next(randomSource)
        } else {
            idValueGen.gen()
        }

    private fun genString(): String = Arb.string(config[StringValueSize]).next(randomSource)

    private fun genOneOf(
        type: GraphQLInputObjectType,
        ctx: Ctx
    ): Map<String, Any?> {
        val field = Arb.of(oneOfCandidates(type, ctx)).next(randomSource)
        return mapOf(field.name to gen(ctx.push(field.type, nullable = false)))
    }

    private fun oneOfCandidates(
        type: GraphQLInputObjectType,
        ctx: Ctx
    ): List<GraphQLInputObjectField> {
        if (!ctx.overBudget) return type.fields
        val cycleGroup = mandatoryEdgesGraph[type.name]
        return type.fields.filter { field ->
            val unwrapped = GraphQLTypeUtil.unwrapAll(field.type)
            unwrapped !is GraphQLInputObjectType ||
                GraphQLTypeUtil.unwrapNonNull(field.type) is GraphQLList ||
                unwrapped.name !in cycleGroup
        }.ifEmpty { type.fields }
    }

    private fun genInputObject(
        type: GraphQLInputObjectType,
        ctx: Ctx
    ): Map<String, Any?> {
        val cycleGroup = allEdgesGraph[type.name]
        return type.fields
            .filter { shouldIncludeField(it, cycleGroup, ctx) }
            .associate { it.name to gen(ctx.push(it.type)) }
    }

    private fun shouldIncludeField(
        field: GraphQLInputObjectField,
        cycleGroup: Set<String>,
        ctx: Ctx
    ): Boolean {
        val inputType = GraphQLTypeUtil.unwrapAll(field.type) as? GraphQLInputObjectType
        if (inputType != null && inputType.name in cycleGroup) return true
        if (!field.hasSetDefaultValue() && field.type is GraphQLNonNull) return true
        return !ctx.overBudget && !randomSource.sampleWeight(config[ImplicitNullValueWeight])
    }

}
