package graphql.arbitrary

import graphql.language.ArrayValue
import graphql.language.BooleanValue
import graphql.language.EnumValue
import graphql.language.FloatValue
import graphql.language.IntValue
import graphql.language.NullValue
import graphql.language.ObjectField
import graphql.language.ObjectValue
import graphql.language.StringValue
import graphql.language.Value
import graphql.schema.GraphQLEnumType
import graphql.schema.GraphQLInputObjectField
import graphql.schema.GraphQLInputObjectType
import graphql.schema.GraphQLInputType
import graphql.schema.GraphQLList
import graphql.schema.GraphQLNonNull
import graphql.schema.GraphQLScalarType
import graphql.schema.GraphQLSchema
import graphql.schema.GraphQLTypeUtil
import io.kotest.property.Arb
import io.kotest.property.RandomSource
import io.kotest.property.arbitrary.int
import io.kotest.property.arbitrary.next
import io.kotest.property.arbitrary.numericDouble
import io.kotest.property.arbitrary.of
import io.kotest.property.arbitrary.string
import java.math.BigDecimal
import java.math.BigInteger

// JMB TODO: lots of overlap between this and the ExternalInputValueGen. Can they be consolidated?

/**
 * Generates GraphQL language AST literals that are valid inputs for a schema type.
 *
 * Generation observes nullability, oneOf semantics, list coercion, defaults, and recursive input
 * object cycles. [uncoercedValueWeight] controls valid literals that rely on input coercion.
 * String ID values are generated by [IDValueGenFactory].
 */
internal class GraphQLInputValueGen(
    schema: GraphQLSchema,
    private val config: Config,
    private val randomSource: RandomSource,
    private val uncoercedValueWeight: Double = 0.0,
    private val allEdgesGraph: CycleGroups = CycleGroups.mandatoryInputCycles(schema),
    private val mandatoryEdgesGraph: CycleGroups = CycleGroups.mandatoryInputCycles(schema)
) {
    private val idValueGen by lazy {
        config[IDValueGenFactory](IDValueGen.Factory.Params(schema, config, randomSource))
    }

    private data class Ctx(
        val type: GraphQLInputType,
        val depth: Int = 0,
        val maxDepth: Int,
        val nullable: Boolean = true
    ) {
        val overBudget: Boolean
            get() = depth >= maxDepth

        fun push(
            nextType: GraphQLInputType,
            nullable: Boolean = nextType !is GraphQLNonNull
        ): Ctx =
            copy(type = nextType, depth = depth + 1, nullable = nullable)

        fun unwrap(
            nextType: GraphQLInputType,
            nullable: Boolean
        ): Ctx = copy(type = nextType, nullable = nullable)
    }

    fun gen(type: GraphQLInputType): Value<*> =
        gen(Ctx(type = type, maxDepth = config[MaxValueDepth]))

    private fun gen(ctx: Ctx): Value<*> {
        val type = ctx.type
        if (type is GraphQLNonNull) {
            return gen(ctx.unwrap(type.wrappedType as GraphQLInputType, nullable = false))
        }
        if (ctx.nullable && shouldGenerateNull(ctx)) {
            return NullValue.newNullValue().build()
        }
        if (type is GraphQLList) return genList(type, ctx)
        if (type is GraphQLScalarType) return genScalar(type)
        if (type is GraphQLEnumType) return genEnum(type)
        if (type is GraphQLInputObjectType && type.isOneOf) {
            return genOneOf(type, ctx)
        }
        if (type is GraphQLInputObjectType) return genInputObject(type, ctx)
        throw UnsupportedOperationException("Unsupported input type: $type")
    }

    private fun shouldGenerateNull(ctx: Ctx): Boolean =
        ctx.overBudget || randomSource.sampleWeight(config[ExplicitNullValueWeight])

    private fun genList(
        listType: GraphQLList,
        ctx: Ctx
    ): Value<*> {
        val wrappedType = listType.wrappedType as GraphQLInputType
        val itemContext = ctx.push(wrappedType)
        val itemCanUseSingleValueCoercion = GraphQLTypeUtil.unwrapNonNull(wrappedType) !is GraphQLList
        if (itemCanUseSingleValueCoercion && !itemContext.overBudget && randomSource.sampleWeight(uncoercedValueWeight)) {
            // A non-list literal is coerced as a single list item. Null is the exception: it
            // represents a null list, so it is not valid after a non-null list has been selected.
            return gen(ctx.push(wrappedType, nullable = false))
        }
        val size = if (itemContext.overBudget) 0 else Arb.int(config[ListValueSize]).next(randomSource)
        val values = List(size) { gen(itemContext) }
        return ArrayValue.newArrayValue().values(values).build()
    }

    private fun genScalar(type: GraphQLScalarType): Value<*> {
        config[ScalarLiteralOverrides][type.name]?.let { return it.next(randomSource) }
        return when (type.name) {
            "Boolean" -> BooleanValue.newBooleanValue(randomSource.random.nextBoolean()).build()
            "Float" -> genFloat()
            "Int" -> IntValue.newIntValue(BigInteger.valueOf(Arb.int().next(randomSource).toLong())).build()
            "ID" -> genId()
            "String" -> genString()
            else -> genString()
        }
    }

    private fun genFloat(): Value<*> {
        if (randomSource.sampleWeight(uncoercedValueWeight)) {
            return IntValue.newIntValue(BigInteger.valueOf(Arb.int().next(randomSource).toLong())).build()
        }
        val value = Arb.numericDouble().next(randomSource)
        return FloatValue.newFloatValue(BigDecimal.valueOf(value)).build()
    }

    private fun genId(): Value<*> {
        if (randomSource.sampleWeight(uncoercedValueWeight)) {
            return IntValue.newIntValue(BigInteger.valueOf(Arb.int().next(randomSource).toLong())).build()
        }
        return StringValue.newStringValue(idValueGen.gen()).build()
    }

    private fun genString(): StringValue =
        StringValue.newStringValue(Arb.string(config[StringValueSize]).next(randomSource)).build()

    private fun genEnum(type: GraphQLEnumType): EnumValue {
        val enumValue = Arb.of(type.values).next(randomSource)
        return EnumValue.newEnumValue(enumValue.name).build()
    }

    private fun genOneOf(
        type: GraphQLInputObjectType,
        ctx: Ctx
    ): ObjectValue {
        val candidates = oneOfCandidates(type, ctx)
        val field = Arb.of(candidates).next(randomSource)
        val value = gen(ctx.push(field.type, nullable = false))
        return objectValue(field.name, value)
    }

    private fun oneOfCandidates(
        type: GraphQLInputObjectType,
        ctx: Ctx
    ): List<GraphQLInputObjectField> {
        if (!ctx.overBudget) return type.fields
        val cycleGroup = mandatoryEdgesGraph[type.name]
        val exits = type.fields.filter { field ->
            val unwrapped = GraphQLTypeUtil.unwrapAll(field.type)
            unwrapped !is GraphQLInputObjectType ||
                GraphQLTypeUtil.unwrapNonNull(field.type) is GraphQLList ||
                unwrapped.name !in cycleGroup
        }
        return exits.ifEmpty { type.fields }
    }

    private fun genInputObject(
        type: GraphQLInputObjectType,
        ctx: Ctx
    ): ObjectValue {
        val cycleGroup = allEdgesGraph[type.name]
        val fields = type.fields.filter { field ->
            shouldIncludeField(field, cycleGroup, ctx)
        }.map { field ->
            ObjectField.newObjectField()
                .name(field.name)
                .value(gen(ctx.push(field.type)))
                .build()
        }
        return ObjectValue.newObjectValue().objectFields(fields).build()
    }

    private fun shouldIncludeField(
        field: GraphQLInputObjectField,
        cycleGroup: Set<String>,
        ctx: Ctx
    ): Boolean {
        val inputType = GraphQLTypeUtil.unwrapAll(field.type) as? GraphQLInputObjectType
        if (inputType != null && inputType.name in cycleGroup) return true
        if (!field.hasSetDefaultValue() && field.type is GraphQLNonNull) return true
        return !ctx.overBudget && !randomSource.sampleWeight(config[ImplicitNullValueWeight])
    }

    private fun objectValue(name: String, value: Value<*>): ObjectValue =
        ObjectValue.newObjectValue()
            .objectField(ObjectField.newObjectField().name(name).value(value).build())
            .build()
}
