@file:Suppress("ForbiddenImport")

package graphql.schema.property

import io.kotest.property.Arb
import io.kotest.property.arbitrary.constant
import io.kotest.property.arbitrary.int
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotEquals
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows

class KotestPropertyBaseTest : KotestPropertyBase() {
    @Test
    fun `checkInvariants throws AssertionError on failure`() {
        assertThrows<AssertionError> {
            runBlocking {
                Arb.constant(true).checkInvariants { v, check ->
                    check.isFalse(v, "test-label")
                }
            }
        }
    }

    @Test
    fun `checkInvariants passes on success`() =
        runBlocking {
            Arb.constant(true).checkInvariants { v, check ->
                check.isTrue(v, "test-label")
            }
        }

    @Test
    fun `configures a seed from ctor`() {
        val base = object : KotestPropertyBase(1L) {}
        assertEquals(1L, base.seed)
        assertEquals(1L, base.randomSource.seed)
    }

    @Test
    fun `configures a random seed by default`() {
        val base = object : KotestPropertyBase() {}
        assertEquals(base.seed, base.randomSource.seed)
    }

    @Test
    fun `randomSource is seeded deterministically`() {
        val a = object : KotestPropertyBase(42L) {}
        val b = object : KotestPropertyBase(42L) {}
        assertEquals(
            Arb.int().generate(a.randomSource).take(10).map { it.value }.toList(),
            Arb.int().generate(b.randomSource).take(10).map { it.value }.toList()
        )
    }

    @Test
    fun `forAll uses instance seed, not global state`() =
        runBlocking {
            // Create two instances with different seeds
            val base1 = object : KotestPropertyBase(1L) {}
            val base2 = object : KotestPropertyBase(2L) {}

            // Collect values generated by forAll from each instance
            val values1 = mutableListOf<Int>()
            val values2 = mutableListOf<Int>()

            with(base1) {
                Arb.int().forAll(10) { v ->
                    values1.add(v)
                    true
                }
            }
            with(base2) {
                Arb.int().forAll(10) { v ->
                    values2.add(v)
                    true
                }
            }

            // Same seed produces same values
            val values1Again = mutableListOf<Int>()
            with(object : KotestPropertyBase(1L) {}) {
                Arb.int().forAll(10) { v ->
                    values1Again.add(v)
                    true
                }
            }
            assertEquals(values1, values1Again, "Same seed should produce same values")
            assertNotEquals(values1, values2, "Different seeds should produce different values")
        }

    @Test
    fun `concurrent instances do not interfere with each other`() =
        runBlocking {
            // Simulate parallel test execution: multiple KotestPropertyBase instances
            // running forAll concurrently, each with a different seed.
            // Each instance should produce deterministic results matching its seed,
            // regardless of interleaving.
            val seeds = (1L..100L).toList()
            val count = 100

            class Tester(seed: Long) : KotestPropertyBase(seed) {
                suspend fun test(): List<Int> {
                    val values = mutableListOf<Int>()
                    Arb.int().forAll(count) { v ->
                        values.add(v)
                        true
                    }
                    return values
                }
            }

            // run each seed concurrently in separate coroutines
            val results = seeds.map { seed ->
                async(Dispatchers.Default) {
                    seed to Tester(seed).test()
                }
            }.awaitAll().toMap()

            // re-run each seed and verify that it produces the same output
            seeds.forEach { seed ->
                val expected = Tester(seed).test()
                assertEquals(expected, results[seed], "Seed $seed produced non-deterministic results under concurrency")
            }
        }
}
